version: "3.9"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: test_nastya
      POSTGRES_USER: slava_test
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
#  app:
#    build:
#      context: ./app
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db