# Generated by Django 5.0.2 on 2024-05-19 13:17

import django.db.models.deletion
import head.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0004_auto_20240514_1507'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='ModelML')),
            ],
            options={
                'verbose_name': 'ModelML',
                'verbose_name_plural': 'ModelML',
            },
        ),
        migrations.AlterModelOptions(
            name='uploadfiles',
            options={'verbose_name': 'upload files', 'verbose_name_plural': 'upload files'},
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='file',
            field=models.FileField(upload_to=head.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
