# Generated by Django 5.0.2 on 2024-05-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0005_modelml_alter_uploadfiles_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='ModelTS')),
            ],
            options={
                'verbose_name': 'ModelTS',
                'verbose_name_plural': 'ModelTS',
            },
        ),
    ]
